# 本地开发数据库配置
spring:
  cloud:
    nacos:
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/shiyiju_local?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

wxpay:
  app-id: wx4b7015f42a4fa49c
  mini-app-id: wx4b7015f42a4fa49c
  mch-id: 1743449441
  mch-key: 2kl4khj788793498fjhksdoisafy9f93
  api-key: 2kl4khj788793498fjhksdoisafy9f93
  notify-url: http://127.0.0.1:8080/pay/callback/notify
