server:
  port: 8090

spring:
  application:
    name: shiyiju-admin
  datasource:
    url: jdbc:mysql://localhost:3306/shiyiju?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
